daemons:
  default:
    context: default
    identifier: traefik-rp

stacks:
  default/traefik:
    root: traefik
    project:
      name: traefik-rp
  default/nginx:
    root: nginx
    project:
      name: traefik-rp
